# Generated by Django 3.2 on 2021-04-28 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='parent_dir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dirs', to='frama.directory'),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='parent_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frama.filesection'),
        ),
    ]
