# Generated by Django 3.2 on 2021-04-29 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frama', '0005_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='statusdata',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='statusdata',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('name', 'parent_dir'), name='unique dir name'),
        ),
    ]
